title: "Kuo Wei's Blog"
description: "Thoughts on AI, software, and life."
author: Kuo Wei
email: WEIKUO0506@gmail.com
url: "https://weikuo0506.github.io"
baseurl: ""  # Root directory
permalink: /:year/:month/:day/:title/

# Use a native GitHub Pages theme with dark appearance
theme: jekyll-theme-slate

# Optional: RSS feed and sitemap for SEO
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Files to exclude from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
  - .jekyll-cache
  - .sass-cache
  - .DS_Store
  - .idea

# GitHub username for profile or linking
github_username: weikuo0506

custom_css:
  - /assets/css/custom.css